// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkNouUEf21qqzYeXeV2bYFptD30AgcXYQ',
    appId: '1:1079346067153:web:1fef19ee2e3b23d4ceb7f0',
    messagingSenderId: '1079346067153',
    projectId: 'flutter-game-21fb8',
    authDomain: 'flutter-game-21fb8.firebaseapp.com',
    storageBucket: 'flutter-game-21fb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoljDpmDY6gcslmOKRyIostxJWra6TnpQ',
    appId: '1:1079346067153:android:919f0ee7556248deceb7f0',
    messagingSenderId: '1079346067153',
    projectId: 'flutter-game-21fb8',
    storageBucket: 'flutter-game-21fb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBttbh_ukY93VZULVNj6e8dvHSupu3LcJA',
    appId: '1:1079346067153:ios:6598f9ae4beda1c2ceb7f0',
    messagingSenderId: '1079346067153',
    projectId: 'flutter-game-21fb8',
    storageBucket: 'flutter-game-21fb8.appspot.com',
    iosClientId: '1079346067153-ajck90s8n9cdldujjs0rav983vhkaeso.apps.googleusercontent.com',
    iosBundleId: 'com.example.newgame',
  );
}
